fix cd final path

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -24,18 +24,21 @@ jobs:
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
-            if [ ! -d ~/github-actions-kubernetes-masterclass ]; then
-              git clone https://github.com/${{ github.repository }}.git ~/github-actions-kubernetes-masterclass
-            fi
+             set -e
 
-            cd ~/github-actions-kubernetes-masterclass
-            git pull origin main
+                if [ ! -d ~/github-actions-kubernetes-masterclass ]; then
+    git clone https://github.com/${{ github.repository }}.git ~/github-actions-kubernetes-masterclass
+  fi
 
-            if [ ! -f .env ]; then
-              echo "ERROR: .env file is missing"
-              exit 1
-            fi
+  cd ~/github-actions-kubernetes-masterclass
 
-            docker compose pull
-            docker compose up -d
-            docker image prune -f
+  git pull origin main
+
+  if [ ! -f .env ]; then
+    echo "ERROR: .env file is missing"
+    exit 1
+  fi
+
+  docker compose pull
+  docker compose up -d
+  docker image prune -f
